//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class canchas
    {
        public canchas()
        {
            this.reservas = new HashSet<reservas>();
            this.tarifas = new HashSet<tarifas>();
        }
    
        public int IdCancha { get; set; }
        public int Establecimientos_IdEstablecimiento { get; set; }
        public string Nombre { get; set; }
        public Nullable<short> Capacidad { get; set; }
        public Nullable<bool> Techo { get; set; }
        public Nullable<short> Calificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual establecimientos establecimientos { get; set; }
        public virtual ICollection<reservas> reservas { get; set; }
        public virtual ICollection<tarifas> tarifas { get; set; }
    }
}
