//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciudades
    {
        public ciudades()
        {
            this.establecimientos = new HashSet<establecimientos>();
        }
    
        public int IdCiudad { get; set; }
        public string Ciudad { get; set; }
        public int Departamento_idDepartamento { get; set; }
    
        public virtual departamentos departamentos { get; set; }
        public virtual ICollection<establecimientos> establecimientos { get; set; }
    }
}
