//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fotoestablecimientos
    {
        public int IdFotoEstablecimiento { get; set; }
        public int Establecimientos_IdEstablecimiento { get; set; }
        public string Foto { get; set; }
    
        public virtual establecimientos establecimientos { get; set; }
    }
}
