//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tucanchaappEntities : DbContext
    {
        public tucanchaappEntities()
            : base("name=tucanchaappEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<canchas> canchas { get; set; }
        public DbSet<ciudades> ciudades { get; set; }
        public DbSet<clientes> clientes { get; set; }
        public DbSet<departamentos> departamentos { get; set; }
        public DbSet<establecimientos> establecimientos { get; set; }
        public DbSet<fotoestablecimientos> fotoestablecimientos { get; set; }
        public DbSet<reservas> reservas { get; set; }
        public DbSet<tarifaprecios> tarifaprecios { get; set; }
        public DbSet<tarifas> tarifas { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
        public DbSet<listadociudades> listadociudades { get; set; }
    }
}
