//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservas
    {
        public int idReserva { get; set; }
        public int Canchas_IdCancha { get; set; }
        public string Clientes_IdCliente { get; set; }
        public string Usuarios_idUsuario { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> HoraReservada { get; set; }
        public string TipoReserva { get; set; }
        public string Estado { get; set; }
        public string Valor { get; set; }
        public string Observaciones { get; set; }
    
        public virtual canchas canchas { get; set; }
        public virtual clientes clientes { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
